version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGO_URI: mongodb://mongodb:27017/your-database
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - "/c/Users/Sagar/Desktop/NewFolder"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379" 
      - "8001:8001"  
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
